### ISSUE TITLE
add chinook db

### ISSUE THREAD

**Issue by morenoh149** [morenoh149/postgresDBSamples#1]
https://github.com/lerocha/chinook-database

**Comment by Paxa** [comment]
Here is file for postgres https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_PostgreSql.sql

Tried to run and got:
```
Chinook_PostgreSql.sql:237: ERROR: invalid byte sequence for encoding "UTF8": 0xf4 0x6e 0x69 0x6f
```
Need to convert file from iso latin to utf8 and it will work:
```
iconv -f ISO-8859-1 -t UTF-8 Chinook_PostgreSql.sql > Chinook_PostgreSql_utf8.sql
```

**Comment by morenoh149** [comment]
@Paxa thanks for the tip! added.
