### ISSUE TITLE
Incorrect copy path for SpecialOfferProduct

### ISSUE THREAD

**Issue by dion-ricky** [morenoh149/postgresDBSamples#11]
https://github.com/morenoh149/postgresDBSamples/blob/d7954d87eb9aee611e881f778164be03916bb4d5/adventureworks/install.sql#L1233

Should be:
```plpgsql
\copy Sales.SpecialOfferProduct FROM './data/SpecialOfferProduct.csv' DELIMITER E'\t' CSV;
```

**Comment by morenoh149** [comment]
please submit a PR

**Comment by jakubiszon** [comment]
I tested the script and can confirm the problem was fixed with commit https://github.com/morenoh149/postgresDBSamples/commit/fb54bee3bc41dd5f0f3dd3db49b310703512f0ea
