### ISSUE TITLE
Adventureworks install.sql contains inconsistent path for some of the .csv files

### ISSUE THREAD

**Issue by pluraltouch** [morenoh149/postgresDBSamples#8]
Adventureworks install.sql contains inconsistent path for some of the .csv files
Some \copy commands refer to the .csv file as ./data/<name>.csv, however some \copy commands are refer just a <name>.csv.

As a consequence there is no current folder where the script can be run without error. 
- If running in the root, then \copy commands which are refer just a <name>.csv will not find the file
- If running in the data folder, then \copy commands refer to the .csv file as ./data/<name>.csv will not find the file

**Comment by morenoh149** [comment]
nice find. Want to submit a pr for that?

**Comment by gabidabet** [comment]
It seems like the issue has been resolved and can now be closed.
